[build]
publish = "public"
command = "hugo --gc --minify"


[context.split1]
command = "hugo --gc --minify --enableGitInfo"


[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"



[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"


[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200